### ISSUE TITLE
[기능추가] Toobar 사용법

### ISSUE THREAD

**Issue by nihil0821** [Limky/Graduation#8]
Toobar를 ReviewActivity.java 파일에서 미리 만들어둔 layout을 setCustomView() 해주면 
 Toobar를 쉽게 꾸밀 수 있음.
다양하게 버튼을 추가 시킬 수도 있음.

**Comment by inhyuck222** [comment]
오 해결 덕분에 해결 했어요 감사합니다!

**Comment by nihil0821** [comment]
toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        //noinspection ConstantConditions
        getSupportActionBar().setDisplayShowCustomEnabled(true);
        getSupportActionBar().setDisplayOptions(ActionBar.DISPLAY_SHOW_CUSTOM);
        getSupportActionBar().setCustomView(getLayoutInflater().inflate(R.layout.actionbar_layout, null),
                new ActionBar.LayoutParams(
                        ActionBar.LayoutParams.WRAP_CONTENT,
                        ActionBar.LayoutParams.MATCH_PARENT,
                        Gravity.CENTER
                )
        );

**Comment by Limky** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ포스코님감사합니다
